const DAY=86400000, TODAY=new Date(); TODAY.setHours(0,0,0,0); const $=s=>document.querySelector(s);
let performances=[],venues=[],filtered=[],config={},meta={},alerts=[],map,markerLayer;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const parse=v=>{if(!v)return null;const d=new Date(v.length===10?v+'T00:00:00+09:00':v);return isNaN(d)?null:d};
const fmt=new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric'}); const venueOf=p=>venues.find(v=>v.id===p.venueId)||{};
function normalizedRegion(v){const text=`${v.city||''} ${v.region||''} ${v.address||''}`;if(/서울/.test(text))return'서울';if(/인천/.test(text))return'인천';if(/경기|부천|김포|고양|수원|성남|용인|안양|광명|시흥|군포|의왕|과천|하남|구리|남양주|파주|양주|의정부|동두천|포천|가평|양평|이천|여주|안성|평택|화성|오산/.test(text))return'경기';return v.city||'지역 미정'}
const days=(a,b=TODAY)=>Math.ceil((parse(a)-b)/DAY); const recent=v=>{const d=parse(v);return d&&(TODAY-d)/DAY<=Number(config.newDays||7)};
function ticketStatus(p){const end=parse(p.endDate);if(end<TODAY||p.ticketSaleStatus==='ENDED')return'종료';if(p.ticketSaleStatus==='SOLD_OUT')return'매진';if(p.ticketOpenDate&&parse(p.ticketOpenDate)>TODAY)return'예매예정';return'예매중/확인';}
function badges(p){const out=[],s=parse(p.startDate),e=parse(p.endDate); if(recent(p.firstSeenAt)||recent(p.updatedAt))out.push(['NEW','new']); if(+s===+TODAY)out.push(['오늘 시작','urgent']);if(+e===+TODAY)out.push(['오늘 종료','urgent']);else if(e>TODAY&&(e-TODAY)/DAY<=Number(config.endingSoonDays||7))out.push(['곧 종료','urgent']);if(p.ticketOpenDate&&ticketStatus(p)==='예매예정')out.push([`예매 D-${days(p.ticketOpenDate)}`,'ticket']);if(p.confidence?.level==='확인 필요')out.push(['정보 확인 필요','warn']);return out.slice(0,3)}
function familyFit(p){const age=p.ageInfo||{};return p.familyTags?.includes('가족추천후보')&&age.minAge!==null&&!age.unknown}
function confidence(p){const c=p.confidence||{};return `<span class="confidence ${c.level==='높음'?'high':c.level==='보통'?'mid':'low'}">신뢰도 ${esc(c.level||'확인 필요')} ${c.score??'-'}</span>`}
function card(p){const v=venueOf(p),poster=p.poster?`<img src="${esc(p.poster)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:'<span class="emoji">🎭</span>';return `<article class="performance-card" data-id="${esc(p.id)}" tabindex="0"><div class="poster">${poster}<div class="badges">${badges(p).map(([t,c])=>`<span class="badge ${c}">${esc(t)}</span>`).join('')}</div></div><div class="card-body"><h3>${esc(p.title)}</h3><div class="meta"><span>${esc(normalizedRegion(v))} ${esc(v.region||'')}</span><span>${fmt.format(parse(p.startDate))}–${fmt.format(parse(p.endDate))}</span></div><p class="age">${esc(p.ageInfo?.label||p.age||'관람연령 확인 필요')}</p><div class="card-foot"><b>${esc(ticketStatus(p))}</b>${confidence(p)}</div></div></article>`}
function render(sel,list){$(sel).innerHTML=list.length?list.map(card).join(''):'<div class="empty">조건에 맞는 공연이 없습니다.</div>'}
function thisWeek(p){const dow=(TODAY.getDay()+6)%7,start=new Date(TODAY.getTime()-dow*DAY),end=new Date(start.getTime()+6*DAY);return parse(p.startDate)<=end&&parse(p.endDate)>=start}
function active(p){return parse(p.endDate)>=TODAY}
function applyFilters(){const q=$('#searchInput').value.trim().toLowerCase(),r=$('#regionFilter').value,a=$('#ageFilter').value,d=$('#dateFilter').value;filtered=performances.filter(p=>{const v=venueOf(p),hay=`${p.title} ${p.genre} ${p.description} ${v.name}`.toLowerCase();return active(p)&&(!q||hay.includes(q))&&(!r||normalizedRegion(v)===r)&&(!a||(a==='family'?familyFit(p):!p.ageInfo?.unknown))&&(!d||(parse(p.startDate)<=parse(d)&&parse(p.endDate)>=parse(d)))});render('#allList',filtered);$('#resultCount').textContent=`${filtered.length}개 공연`;refreshMarkers()}
function links(p,v){const booking=(p.bookingUrls||[]).map(x=>`<a target="_blank" rel="noopener" href="${esc(x.url)}">${esc(x.name||'예매')}</a>`).join('');const maplinks=v.address?`<a target="_blank" rel="noopener" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(v.address)}">Google 지도</a><a target="_blank" rel="noopener" href="https://map.kakao.com/link/search/${encodeURIComponent(v.address)}">카카오맵</a><a target="_blank" rel="noopener" href="https://map.naver.com/p/search/${encodeURIComponent(v.address)}">네이버 지도</a>`:'';return booking+maplinks+`<a target="_blank" rel="noopener" href="${esc(p.sourceUrl)}">KOPIS 원문</a>`}
function openDetail(id){const p=performances.find(x=>x.id===id),v=venueOf(p);if(!p)return;const checks=p.confidence?.checks||{};$('#detailContent').innerHTML=`<div class="detail-hero"><div class="badges">${badges(p).map(([t,c])=>`<span class="badge ${c}">${esc(t)}</span>`).join('')}</div><h2>${esc(p.title)}</h2><p>${esc(p.description)}</p></div><div class="detail-body"><div class="detail-grid"><div class="info-box"><b>공연 기간</b><p>${esc(p.startDate)} ~ ${esc(p.endDate)}</p></div><div class="info-box"><b>관람 연령</b><p>${esc(p.ageInfo?.label||'확인 필요')}</p></div><div class="info-box"><b>공연장</b><p>${esc(v.name||'미정')}<br>${esc(v.address||'주소 확인 필요')}</p></div><div class="info-box"><b>가격·시간</b><p>${esc(p.price||'가격 확인 필요')}<br>${esc(p.runtime||'공연시간 확인 필요')}</p></div></div><section class="verification"><h3>정보 정확도</h3>${confidence(p)}<ul><li>${checks.officialSource?'✓':'!'} 공식 KOPIS 출처</li><li>${checks.age?'✓':'!'} 관람연령 ${checks.age?'확인됨':'원문 확인 필요'}</li><li>${checks.booking?'✓':'!'} 예매 링크 ${checks.booking?'확인됨':'원문에서 확인 필요'}</li><li>마지막 확인: ${esc(p.lastCheckedAt||'-')}</li></ul></section><div class="map-links">${links(p,v)}</div></div>`;injectLd(p,v);$('#detailDialog').showModal()}
function injectLd(p,v){$('#eventJsonLd')?.remove();const s=document.createElement('script');s.id='eventJsonLd';s.type='application/ld+json';s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'Event',name:p.title,startDate:p.startDate,endDate:p.endDate,image:p.poster?[p.poster]:undefined,location:{'@type':'Place',name:v.name,address:v.address,geo:v.latitude?{'@type':'GeoCoordinates',latitude:v.latitude,longitude:v.longitude}:undefined},offers:(p.bookingUrls||[])[0]?{'@type':'Offer',url:p.bookingUrls[0].url}:undefined});document.head.appendChild(s)}
async function loadMap(){if(map)return;await Promise.all([new Promise((ok,fail)=>{const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.onload=ok;l.onerror=fail;document.head.appendChild(l)}),new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=ok;s.onerror=fail;document.body.appendChild(s)})]);$('#mapPlaceholder').hidden=true;$('#map').hidden=false;map=L.map('map').setView([37.45,126.85],9);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map);markerLayer=L.layerGroup().addTo(map);refreshMarkers()}
function refreshMarkers(){if(!map||!markerLayer)return;markerLayer.clearLayers();const groups={};filtered.forEach(p=>(groups[p.venueId]??=[]).push(p));Object.entries(groups).forEach(([id,list])=>{const v=venues.find(x=>x.id===id);if(!v?.latitude||!v?.longitude)return;L.marker([v.latitude,v.longitude]).addTo(markerLayer).bindPopup(`<b>${esc(v.name)}</b>${list.map(p=>`<button class="popup-btn" data-popup-id="${esc(p.id)}">${esc(p.title)}</button>`).join('')}`)})}
function nearby(){const msg=$('#nearbyMessage');if(!navigator.geolocation){msg.textContent='위치 기능을 지원하지 않습니다.';return}msg.textContent='위치 확인 중…';navigator.geolocation.getCurrentPosition(pos=>{const lat=pos.coords.latitude,lon=pos.coords.longitude,dist=v=>{if(!v.latitude)return 99999;const r=Math.PI/180,a=.5-Math.cos((v.latitude-lat)*r)/2+Math.cos(lat*r)*Math.cos(v.latitude*r)*(1-Math.cos((v.longitude-lon)*r))/2;return 12742*Math.asin(Math.sqrt(a))};const list=performances.filter(active).sort((a,b)=>dist(venueOf(a))-dist(venueOf(b))).slice(0,8);render('#nearbyList',list);msg.textContent='현재 위치에서 가까운 순서입니다.'},()=>msg.textContent='위치 권한이 거부되었습니다.')}
async function init(){[config,venues,performances,meta,alerts]=await Promise.all(['config.json','data/venues.json','data/performances.json','data/sync-meta.json','data/alerts.json'].map(u=>fetch(u,{cache:'no-store'}).then(r=>r.ok?r.json():[])));filtered=performances.filter(active);const updated=parse(meta.updatedAt),hours=updated?(Date.now()-updated)/3600000:999;$('#dataStatus').innerHTML=`<b>${meta.source||'공식 데이터'}</b> · ${meta.performanceCount||performances.length}개 · 마지막 확인 ${updated?updated.toLocaleString('ko-KR'):'알 수 없음'} ${hours>Number(config.staleHours||30)?'<strong>⚠ 갱신 지연</strong>':'<span>정상 갱신</span>'}`;$('#watchKeywords').textContent=(config.watchKeywords||[]).join(' · ');$('#footerMeta').textContent=`마지막 데이터 확인: ${meta.updatedAt||'-'} / 출처: ${meta.source||'-'}`;['서울','인천','경기'].forEach(x=>$('#regionFilter').insertAdjacentHTML('beforeend',`<option value="${x}">${x}</option>`));const watchIds=new Set(alerts.filter(a=>a.type==='WATCH_MATCH').map(a=>a.performanceId));render('#watchList',performances.filter(p=>watchIds.has(p.id)&&active(p)).slice(0,12));render('#familyList',performances.filter(p=>active(p)&&familyFit(p)).sort((a,b)=>(b.confidence?.score||0)-(a.confidence?.score||0)).slice(0,12));render('#newList',performances.filter(p=>active(p)&&(recent(p.firstSeenAt)||recent(p.updatedAt))).sort((a,b)=>parse(b.updatedAt)-parse(a.updatedAt)).slice(0,12));render('#weekList',performances.filter(p=>active(p)&&thisWeek(p)).slice(0,12));render('#allList',filtered);$('#resultCount').textContent=`${filtered.length}개 공연`;['#searchInput','#regionFilter','#ageFilter','#dateFilter'].forEach(s=>$(s).addEventListener('input',applyFilters));$('#nearbyButton').onclick=nearby;$('#loadMapButton').onclick=loadMap;$('.dialog-close').onclick=()=>$('#detailDialog').close();document.addEventListener('click',e=>{const c=e.target.closest('[data-id]');if(c)openDetail(c.dataset.id);const p=e.target.closest('[data-popup-id]');if(p)openDetail(p.dataset.popupId)});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.matches('[data-id]'))openDetail(e.target.dataset.id)});new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting))loadMap()},{rootMargin:'250px'}).observe($('#mapPlaceholder'))}
init().catch(e=>{console.error(e);$('#dataStatus').textContent='데이터를 불러오지 못했습니다. GitHub Actions 실행 상태를 확인하세요.'});
