const state={places:[],filtered:[],features:new Set(),favorites:new Set(JSON.parse(localStorage.getItem('twoKidsFavorites')||'[]'))};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const labels={"kids-cafe":"공공 키즈카페",library:"어린이도서관",museum:"박물관·체험관",playground:"실내놀이터"};
const featureLabels={indoor:"실내",stroller:"유모차",nursingRoom:"수유실",diaperTable:"기저귀 교환대",parking:"주차",elevator:"엘리베이터",reservationFree:"예약 없이",free:"무료·저렴"};
const clamp=(n,min=0,max=100)=>Math.max(min,Math.min(max,n));
function yearAge(year){const birth=Number(year);return Math.max(0,new Date().getFullYear()-birth)}
function childAges(){return {first:yearAge($('#firstYear').value),baby:yearAge($('#secondYear').value)}}
function updateAges(){const a=$('#firstYear').value,b=$('#secondYear').value;localStorage.setItem('twoKidsYears',JSON.stringify([a,b]));const ages=childAges();$('#ageSummary').textContent=`연나이 기준 첫째 ${ages.first}세 · 둘째 ${ages.baby}세를 실제 추천 점수에 반영해요.`}
function ageFit(age,p){const min=Number.isFinite(p.ageMin)?p.ageMin:0,max=Number.isFinite(p.ageMax)?p.ageMax:12;if(age>=min&&age<=max)return 100;const gap=age<min?min-age:age-max;return clamp(55-gap*25)}
function scoreParts(p){const ages=childAges();const firstFit=ageFit(ages.first,p),babyFit=ageFit(ages.baby,p);const first=Math.round(p.scores.first*.62+firstFit*.38);const babyFacilities=(p.features.stroller?20:0)+(p.features.nursingRoom?28:0)+(p.features.diaperTable?24:0)+(p.features.elevator?13:0)+(p.features.indoor?15:0);const baby=Math.round(p.scores.baby*.42+babyFit*.38+babyFacilities*.20);return {first:clamp(first),baby:clamp(baby),firstFit,babyFit,solo:p.scores.solo,parent:p.scores.parent}}
function familyScore(p){const s=scoreParts(p);let total=$('#guardianMode').value==='solo'?s.first*.25+s.baby*.30+s.solo*.30+s.parent*.15:s.first*.34+s.baby*.31+s.parent*.25+s.solo*.10;if(s.firstFit<60||s.babyFit<60)total-=18;if(!p.verified)total-=4;return clamp(Math.round(total))}
function matches(p){if($('#region').value!=='all'&&p.region!==$('#region').value)return false;if($('#category').value!=='all'&&p.category!==$('#category').value)return false;const d=$('#duration').value;if(d==='short'&&p.stayMinutes>100)return false;if(d==='half'&&(p.stayMinutes<100||p.stayMinutes>260))return false;for(const f of state.features){if(!p.features[f])return false}return true}
function reason(p){const ages=childAges(),s=scoreParts(p);if(s.firstFit<60)return `첫째 ${ages.first}세가 공식 이용연령(${p.ageMin}~${p.ageMax}세)과 맞지 않을 수 있어요.`;if(s.babyFit<60)return `둘째 ${ages.baby}세가 공식 이용연령(${p.ageMin}~${p.ageMax}세)과 맞지 않을 수 있어요.`;if(s.baby>=88)return '두 아이의 연령이 맞고 유모차·영아 편의 조건도 좋은 편이에요.';if(s.solo>=85)return '보호자 한 명이 두 아이를 데리고 가기 비교적 편한 곳이에요.';if(s.first>=88)return '첫째가 충분히 놀 수 있고 둘째도 함께 입장 가능한 곳이에요.';return '두 아이의 연령과 보호자 동선을 함께 고려한 추천이에요.'}
function safeUrl(url){try{const u=new URL(url,location.href);return ['http:','https:'].includes(u.protocol)?u.href:'#'}catch{return '#'}}
function render(){state.filtered=state.places.filter(matches);const mode=$('#sort').value;state.filtered.sort((a,b)=>mode==='score'?familyScore(b)-familyScore(a):scoreParts(b)[mode]-scoreParts(a)[mode]);$('#resultCount').textContent=state.filtered.length;$('#empty').hidden=state.filtered.length>0;const box=$('#cards');box.innerHTML='';for(const p of state.filtered){const s=scoreParts(p),node=$('#cardTemplate').content.cloneNode(true);node.querySelector('.card').dataset.id=p.id;node.querySelector('.category-badge').textContent=labels[p.category]||p.category;node.querySelector('h3').textContent=p.name;node.querySelector('.address').textContent=`${p.region} · ${p.address}`;const score=familyScore(p),circle=node.querySelector('.total-score');circle.style.setProperty('--score',score);circle.querySelector('strong').textContent=score;node.querySelector('.mini-scores').innerHTML=`<div class="mini"><strong>${s.first}</strong><span>첫째 적합</span></div><div class="mini"><strong>${s.baby}</strong><span>둘째 적합</span></div><div class="mini"><strong>${s.solo}</strong><span>혼자 편의</span></div>`;node.querySelector('.reason').textContent=reason(p);const tags=Object.entries(p.features).filter(([,v])=>v).map(([k])=>`<span class="tag ${['stroller','nursingRoom','diaperTable'].includes(k)?'good':''}">${featureLabels[k]||k}</span>`);tags.unshift(`<span class="tag age-tag">이용 ${p.ageMin}~${p.ageMax}세</span>`);if(!p.verified)tags.push('<span class="tag caution">편의정보 확인 필요</span>');node.querySelector('.tags').innerHTML=tags.join('');const fav=node.querySelector('.favorite');fav.textContent=state.favorites.has(p.id)?'♥':'♡';fav.classList.toggle('active',state.favorites.has(p.id));fav.onclick=()=>toggleFavorite(p.id);const official=node.querySelector('.official'),url=safeUrl(p.url);official.href=url;if(url==='#'){official.hidden=true}node.querySelector('.map').href=`https://map.kakao.com/link/search/${encodeURIComponent(p.name+' '+p.address)}`;box.appendChild(node)}}
function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('twoKidsFavorites',JSON.stringify([...state.favorites]));render()}
function fillRegions(){const regions=[...new Set(state.places.map(p=>p.region))].sort();$('#region').innerHTML='<option value="all">전체</option>'+regions.map(r=>`<option value="${r}">${r}</option>`).join('')}
function pick(){if(!state.filtered.length)return;const pool=state.filtered.slice(0,Math.min(8,state.filtered.length)),p=pool[Math.floor(Math.random()*pool.length)],url=safeUrl(p.url);$('#pickContent').innerHTML=`<div class="pick-score">${familyScore(p)}점</div><h2 class="pick-title">${p.name}</h2><p>${reason(p)}</p><p>${p.region} · ${p.address}</p><p class="age-summary">공식 이용연령 ${p.ageMin}~${p.ageMax}세</p><div class="card-actions">${url==='#'?'':`<a class="official" target="_blank" rel="noopener noreferrer" href="${url}">공식 정보</a>`}<a class="map" target="_blank" rel="noopener noreferrer" href="https://map.kakao.com/link/search/${encodeURIComponent(p.name+' '+p.address)}">지도 보기</a></div>`;$('#pickDialog').showModal()}
function validatePlace(p){return p&&p.id&&p.name&&p.address&&p.region&&p.features&&p.scores&&Number.isFinite(p.ageMin)&&Number.isFinite(p.ageMax)&&p.ageMin<=p.ageMax}
async function init(){const saved=JSON.parse(localStorage.getItem('twoKidsYears')||'["2022","2026"]');[$('#firstYear').value,$('#secondYear').value]=saved;updateAges();try{const res=await fetch('./data/places.json',{cache:'no-store'});if(!res.ok)throw Error('data');const data=await res.json();state.places=(data.places||[]).filter(validatePlace);$('#updatedAt').textContent=new Date(data.updatedAt).toLocaleString('ko-KR');$('#sourceNote').textContent=data.sourceNote||'';fillRegions();render()}catch(e){$('#cards').innerHTML='<div class="empty"><strong>데이터를 불러오지 못했습니다.</strong><p>잠시 후 새로고침해 주세요.</p></div>'}}
$('#saveYears').onclick=()=>{updateAges();render()};$('#randomPick').onclick=pick;$('#closeDialog').onclick=()=>$('#pickDialog').close();$('#resetFilters').onclick=()=>{$('#region').value='all';$('#category').value='all';$('#guardianMode').value='solo';$('#duration').value='all';state.features.clear();$$('#featureFilters button').forEach(b=>b.classList.remove('active'));render()};$$('#featureFilters button').forEach(b=>b.onclick=()=>{const f=b.dataset.feature;state.features.has(f)?state.features.delete(f):state.features.add(f);b.classList.toggle('active');render()});['region','category','guardianMode','duration','sort'].forEach(id=>$('#'+id).onchange=render);init();
