const state={places:[],filtered:[],features:new Set(),favorites:new Set(JSON.parse(localStorage.getItem('twoKidsFavorites')||'[]'))};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const labels={"kids-cafe":"공공 키즈카페",library:"어린이도서관",museum:"박물관·체험관",playground:"실내놀이터"};
const featureLabels={indoor:"실내",stroller:"유모차",nursingRoom:"수유실",diaperTable:"기저귀 교환대",parking:"주차",elevator:"엘리베이터",reservationFree:"예약 없이",free:"무료·저렴"};
function koreanAge(year){const now=new Date();const birth=Number(year);return Math.max(0,now.getFullYear()-birth)}
function updateAges(){const a=$('#firstYear').value,b=$('#secondYear').value;localStorage.setItem('twoKidsYears',JSON.stringify([a,b]));$('#ageSummary').textContent=`현재 기준 첫째 약 ${koreanAge(a)}세 · 둘째 약 ${koreanAge(b)}세에 맞춰 추천해요.`}
function familyScore(p){let first=p.scores.first,baby=p.scores.baby,solo=p.scores.solo,parent=p.scores.parent;if($('#guardianMode').value==='solo')return Math.round(first*.28+baby*.28+solo*.29+parent*.15);return Math.round(first*.35+baby*.30+parent*.25+solo*.10)}
function matches(p){if($('#region').value!=='all'&&p.region!==$('#region').value)return false;if($('#category').value!=='all'&&p.category!==$('#category').value)return false;const d=$('#duration').value;if(d==='short'&&p.stayMinutes>100)return false;if(d==='half'&&(p.stayMinutes<100||p.stayMinutes>260))return false;for(const f of state.features){if(!p.features[f])return false}return true}
function reason(p){const best=Object.entries(p.scores).sort((a,b)=>b[1]-a[1])[0][0];const map={first:"첫째가 충분히 움직이며 놀기 좋아요.",baby:"유모차와 영아 편의시설이 잘 갖춰진 편이에요.",solo:"보호자 한 명이 두 아이를 데리고 가기 비교적 편해요.",parent:"주차·휴식·동선 측면에서 보호자 부담이 적어요."};return map[best]}
function render(){state.filtered=state.places.filter(matches);const mode=$('#sort').value;state.filtered.sort((a,b)=>{if(mode==='score')return familyScore(b)-familyScore(a);return b.scores[mode]-a.scores[mode]});$('#resultCount').textContent=state.filtered.length;$('#empty').hidden=state.filtered.length>0;const box=$('#cards');box.innerHTML='';for(const p of state.filtered){const node=$('#cardTemplate').content.cloneNode(true);const art=node.querySelector('.card');art.dataset.id=p.id;node.querySelector('.category-badge').textContent=labels[p.category]||p.category;node.querySelector('h3').textContent=p.name;node.querySelector('.address').textContent=`${p.region} · ${p.address}`;const score=familyScore(p);const circle=node.querySelector('.total-score');circle.style.setProperty('--score',score);circle.querySelector('strong').textContent=score;node.querySelector('.mini-scores').innerHTML=`<div class="mini"><strong>${p.scores.first}</strong><span>첫째 재미</span></div><div class="mini"><strong>${p.scores.baby}</strong><span>둘째 편의</span></div><div class="mini"><strong>${p.scores.solo}</strong><span>혼자 난이도</span></div>`;node.querySelector('.reason').textContent=reason(p);node.querySelector('.tags').innerHTML=Object.entries(p.features).filter(([,v])=>v).map(([k])=>`<span class="tag ${['stroller','nursingRoom','diaperTable'].includes(k)?'good':''}">${featureLabels[k]||k}</span>`).join('');const fav=node.querySelector('.favorite');fav.textContent=state.favorites.has(p.id)?'♥':'♡';fav.classList.toggle('active',state.favorites.has(p.id));fav.onclick=()=>toggleFavorite(p.id);node.querySelector('.official').href=p.url;node.querySelector('.map').href=`https://map.kakao.com/link/search/${encodeURIComponent(p.name+' '+p.address)}`;box.appendChild(node)}}
function toggleFavorite(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);localStorage.setItem('twoKidsFavorites',JSON.stringify([...state.favorites]));render()}
function fillRegions(){const regions=[...new Set(state.places.map(p=>p.region))].sort();$('#region').innerHTML='<option value="all">전체</option>'+regions.map(r=>`<option>${r}</option>`).join('')}
function pick(){if(!state.filtered.length)return;const pool=state.filtered.slice(0,Math.min(8,state.filtered.length));const p=pool[Math.floor(Math.random()*pool.length)];$('#pickContent').innerHTML=`<div class="pick-score">${familyScore(p)}점</div><h2 class="pick-title">${p.name}</h2><p>${reason(p)}</p><p>${p.region} · ${p.address}</p><div class="card-actions"><a class="official" target="_blank" rel="noopener noreferrer" href="${p.url}">공식 정보</a><a class="map" target="_blank" rel="noopener noreferrer" href="https://map.kakao.com/link/search/${encodeURIComponent(p.name+' '+p.address)}">지도 보기</a></div>`;$('#pickDialog').showModal()}
async function init(){const saved=JSON.parse(localStorage.getItem('twoKidsYears')||'["2022","2026"]');[$('#firstYear').value,$('#secondYear').value]=saved;updateAges();try{const res=await fetch('./data/places.json',{cache:'no-store'});if(!res.ok)throw Error('data');const data=await res.json();state.places=data.places;$('#updatedAt').textContent=new Date(data.updatedAt).toLocaleString('ko-KR');fillRegions();render()}catch(e){$('#cards').innerHTML='<div class="empty"><strong>데이터를 불러오지 못했습니다.</strong><p>로컬에서 파일을 직접 열었다면 간단한 웹서버로 실행하세요.</p></div>'}}
$('#saveYears').onclick=()=>{updateAges();render()};$('#randomPick').onclick=pick;$('#closeDialog').onclick=()=>$('#pickDialog').close();$('#resetFilters').onclick=()=>{$('#region').value='all';$('#category').value='all';$('#guardianMode').value='solo';$('#duration').value='all';state.features.clear();$$('#featureFilters button').forEach(b=>b.classList.remove('active'));render()};$$('#featureFilters button').forEach(b=>b.onclick=()=>{const f=b.dataset.feature;state.features.has(f)?state.features.delete(f):state.features.add(f);b.classList.toggle('active');render()});['region','category','guardianMode','duration','sort'].forEach(id=>$('#'+id).onchange=render);init();
